/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.NhapHangController;
import Model.*;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Action;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author H
 */
public class NhapHangView extends javax.swing.JFrame {

    QuanLyKhoModel model;

    /**
     * Creates new form NhapHangView
     */
    public NhapHangView() throws ClassNotFoundException, SQLException {
        initComponents();
        model = new QuanLyKhoModel();
        loadJTablePhieu();
        loadJCombobox();
        Action action = new NhapHangController(this);
        btnLamMoi.addActionListener(action);
        btnSuaTt.addActionListener(action);
        btnThemPhieu.addActionListener(action);
        btnThemTt.addActionListener(action);
        btnTim.addActionListener(action);
        btnXoaPhieu.addActionListener(action);
        btnXoaTt.addActionListener(action);
        cbbHangHoa.addActionListener(action);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPhieu = new javax.swing.JTable();
        btnThemPhieu = new javax.swing.JButton();
        btnXoaPhieu = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfSoLuong = new javax.swing.JTextField();
        tfDonGia = new javax.swing.JTextField();
        cbbN = new javax.swing.JComboBox<>();
        cbbHangHoa = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblThongTinPhieu = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        cbbKhoTimKiem = new javax.swing.JComboBox<>();
        btnThemTt = new javax.swing.JButton();
        btnSuaTt = new javax.swing.JButton();
        btnXoaTt = new javax.swing.JButton();
        btnTim = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jlb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nhập hàng");

        tblPhieu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblPhieu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã phiếu", "Ngày tạo"
            }
        ));
        tblPhieu.setRowHeight(30);
        tblPhieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPhieuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPhieu);

        btnThemPhieu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnThemPhieu.setText("Tạo phiếu");

        btnXoaPhieu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnXoaPhieu.setText("Xoá phiếu");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Nhà cung cấp");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Hàng hoá");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Số lượng");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Đơn giá");

        tfSoLuong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tfDonGia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        cbbN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        cbbHangHoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tblThongTinPhieu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblThongTinPhieu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nhà cung cấp", "Hàng hoá", "Số lượng", "Đơn giá"
            }
        ));
        tblThongTinPhieu.setRowHeight(30);
        tblThongTinPhieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblThongTinPhieuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblThongTinPhieu);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Tìm theo Tên hàng");

        cbbKhoTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnThemTt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnThemTt.setText("Thêm tt");

        btnSuaTt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSuaTt.setText("Sửa tt");

        btnXoaTt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnXoaTt.setText("Xoá tt");

        btnTim.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTim.setText("Tìm");

        btnLamMoi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLamMoi.setText("Làm mới");

        jLabel1.setText("Còn lại:");

        jlb.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnXoaPhieu, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(btnThemPhieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1)
                        .addGap(27, 27, 27)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbbHangHoa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbbN, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfDonGia)
                    .addComponent(tfSoLuong, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlb)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTim, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(165, 165, 165))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbKhoTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 186, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(416, 416, 416)
                        .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnThemTt, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btnSuaTt, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnXoaTt, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(156, 156, 156))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnThemPhieu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnXoaPhieu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbbKhoTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTim))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(jlb))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbbHangHoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tfSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemTt)
                    .addComponent(btnSuaTt)
                    .addComponent(btnXoaTt)
                    .addComponent(btnLamMoi))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblPhieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPhieuMouseClicked
        String id = getTextSelectedIdPhieu();
        try {
            loadJTableTtPhieu(id);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NhapHangView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(NhapHangView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_tblPhieuMouseClicked

    private void tblThongTinPhieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThongTinPhieuMouseClicked
        int dongchon = 0;
        dongchon = tblThongTinPhieu.getSelectedRow();
        String ncc = tblThongTinPhieu.getValueAt(dongchon, 1) + "";
        String hh = tblThongTinPhieu.getValueAt(dongchon, 2) + "";
        String sl = tblThongTinPhieu.getValueAt(dongchon, 3) + "";
        String dg = tblThongTinPhieu.getValueAt(dongchon, 4) + "";
        cbbN.setSelectedItem(ncc);
        cbbHangHoa.setSelectedItem(hh);
        tfSoLuong.setText(sl);
        tfDonGia.setText(dg);
    }//GEN-LAST:event_tblThongTinPhieuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhapHangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhapHangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhapHangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhapHangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new NhapHangView().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(NhapHangView.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(NhapHangView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSuaTt;
    private javax.swing.JButton btnThemPhieu;
    private javax.swing.JButton btnThemTt;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoaPhieu;
    private javax.swing.JButton btnXoaTt;
    private javax.swing.JComboBox<String> cbbHangHoa;
    private javax.swing.JComboBox<String> cbbKhoTimKiem;
    private javax.swing.JComboBox<String> cbbN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlb;
    private javax.swing.JTable tblPhieu;
    private javax.swing.JTable tblThongTinPhieu;
    private javax.swing.JTextField tfDonGia;
    private javax.swing.JTextField tfSoLuong;
    // End of variables declaration//GEN-END:variables

    public void loadJTablePhieu() throws ClassNotFoundException, SQLException {
        int i = 0;
        model = new QuanLyKhoModel();
        for (Phieunhap item : model.phieunhaps) {
            DefaultTableModel model = (DefaultTableModel) tblPhieu.getModel();
            model.setRowCount(i + 1);
            tblPhieu.setValueAt(item.getMaPN(), i, 0);
            tblPhieu.setValueAt(item.getNgayNhap(), i, 1);
            i++;
        }

    }

    public void loadJTableTtPhieu(String idPhieu) throws ClassNotFoundException, SQLException {
        int i = 0;
        model = new QuanLyKhoModel();
        DefaultTableModel m = (DefaultTableModel) tblThongTinPhieu.getModel();
        m.setRowCount(0);
        for (Ttphieunhap item : model.ttphieunhaps) {
            if (item.getMaPN().getMaPN().equals(idPhieu)) {
                m.setRowCount(i + 1);
                tblThongTinPhieu.setValueAt(item.getId(), i, 0);
                tblThongTinPhieu.setValueAt(item.getMaNCC().getTenNCC(), i, 1);
                tblThongTinPhieu.setValueAt(item.getMaHang().getTenHang(), i, 2);
                tblThongTinPhieu.setValueAt(item.getSLNhap(), i, 3);
                tblThongTinPhieu.setValueAt(item.getDGNhap(), i, 4);
                i++;
            }
        }
    }

    public void setJTableTtPhieu(ArrayList<Ttphieunhap> lstPhieu) throws ClassNotFoundException, SQLException {
        int i = 0;
        model = new QuanLyKhoModel();
        for (Ttphieunhap item : lstPhieu) {
            DefaultTableModel model = (DefaultTableModel) tblThongTinPhieu.getModel();
            model.setRowCount(i + 1);
            tblThongTinPhieu.setValueAt(item.getId(), i, 0);
            tblThongTinPhieu.setValueAt(item.getMaNCC().getTenNCC(), i, 1);
            tblThongTinPhieu.setValueAt(item.getMaHang().getTenHang(), i, 2);
            tblThongTinPhieu.setValueAt(item.getSLNhap(), i, 3);
            tblThongTinPhieu.setValueAt(item.getDGNhap(), i, 4);
            i++;

        }
    }

    public void loadJCombobox() {
        for (Nhacungcap item : model.nhacungcaps) {
            cbbN.addItem(item.getTenNCC());
        }
        for (Hanghoa item : model.hanghoas) {
            cbbHangHoa.addItem(item.getTenHang());
            cbbKhoTimKiem.addItem(item.getTenHang());
        }
    }

    public String getTextSelectedIdPhieu() {
        int dongchon = tblPhieu.getSelectedRow();
        String ID = tblPhieu.getValueAt(dongchon, 0) + "";
        return ID;
    }

    public String getTextSelectedIdTtPhieu() {
        int dongchon = tblThongTinPhieu.getSelectedRow();
        String ID = tblThongTinPhieu.getValueAt(dongchon, 0) + "";
        return ID;
    }

    public String getTextTfSoLuong() {
        return tfSoLuong.getText();
    }

    public String getTextTfDonGia() {
        return tfDonGia.getText();
    }

    public String getTextCbbN() {
        String string = cbbN.getSelectedItem().toString();
        for (Nhacungcap item : model.nhacungcaps) {
            if (item.getTenNCC().equals(string)) {
                return item.getMaNCC();
            }
        }
        return "";
    }

    public String getTextCbbHangHoa() {
        String string = cbbHangHoa.getSelectedItem().toString();
        for (Hanghoa item : model.hanghoas) {
            if (item.getTenHang().equals(string)) {
                return item.getMaHang();
            }
        }
        return "";
    }

    public String getTextCbbKhoTimKiem() {
        return cbbKhoTimKiem.getSelectedItem().toString();
    }

    public void clear() {
        tfDonGia.setText("");
        tfSoLuong.setText("");
    }

    public void setLbTonKho(String str) {
        jlb.setText(str);
    }

    public int getIndexTblPhieu() {
        return tblPhieu.getSelectedRow();
    }
    
    public int getIndexTblTtPhieu() {
        return tblThongTinPhieu.getSelectedRow();
    }
}
